services:
  - type: web
    name: moving-company-app
    env: python
    buildCommand: pip install -r requirements.txt && cd backend && python manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: moving-company-app.onrender.com
    healthCheckPath: /

